# Решение оптимизационных задач в SciPy

In [1]:
from scipy import optimize

In [2]:
def f(x):   # The rosenbrock function
    return .5*(1 - x[0])**2 + (x[1] - x[0]**2)**2
    
print f([1, 1])

0.0


In [3]:
result = optimize.brute(f, ((-5, 5), (-5, 5)))
print result

[ 0.99999324  1.00001283]


In [4]:
print optimize.differential_evolution(f, ((-5, 5), (-5, 5)))

    nfev: 1803
 success: True
     fun: 1.9180451127782141e-20
       x: array([ 1.,  1.])
 message: 'Optimization terminated successfully.'
     nit: 59


In [5]:
import numpy as np

def g(x):
        return np.array((-2*.5*(1 - x[0]) - 4*x[0]*(x[1] - x[0]**2), 2*(x[1] - x[0]**2)))

In [6]:
print optimize.check_grad(f, g, [2, 2])

2.38418579102e-07


In [7]:
print optimize.fmin_bfgs(f, [2, 2], fprime=g)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 16
         Function evaluations: 24
         Gradient evaluations: 24
[ 1.00000017  1.00000026]


In [8]:
print optimize.minimize(f, [2, 2])

   status: 0
  success: True
     njev: 24
     nfev: 96
 hess_inv: array([[ 0.98632031,  1.97824298],
       [ 1.97824298,  4.46512254]])
      fun: 9.536835216356594e-15
        x: array([ 1.00000007,  1.00000005])
  message: 'Optimization terminated successfully.'
      jac: array([  4.74151523e-07,  -1.53924328e-07])


In [9]:
print optimize.minimize(f, [2, 2], method='BFGS')

   status: 0
  success: True
     njev: 24
     nfev: 96
 hess_inv: array([[ 0.98632031,  1.97824298],
       [ 1.97824298,  4.46512254]])
      fun: 9.536835216356594e-15
        x: array([ 1.00000007,  1.00000005])
  message: 'Optimization terminated successfully.'
      jac: array([  4.74151523e-07,  -1.53924328e-07])


In [1]:
print optimize.minimize(f, [2, 2], method='Nelder-Mead')

NameError: name 'optimize' is not defined

In [5]:
import numpy

In [6]:
c = numpy.array([False, False, True])

In [8]:
print c

[False False  True]


In [10]:
b = numpy.array([1, 2, 3, 4, 5], dtype=float)

In [11]:
print b

[ 1.  2.  3.  4.  5.]


In [12]:
f = numpy.arange(1, 2, 0.3, dtype=float)

In [13]:
print f

[ 1.   1.3  1.6  1.9]


In [16]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])
numpy.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [20]:
a = numpy.array([0, -1, 11])
b = numpy.array([3, 7, 2])
b.dot(a)
numpy.dot(a, b)

15

In [27]:
a = numpy.array([8, 10, -1, 0, 0])
a = a.reshape((1, 5))
print a

[[ 8 10 -1  0  0]]


In [28]:
import scipy

In [33]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])
print (7**2+3**2+12**2)**0.5

14.2126704036


In [35]:
scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [38]:
b = np.eye(2)


e = np.arange(1, 13, 2).reshape((3, 2))


d = np.ones((10, 10))


#c = np.eye((4, 5))


#a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

In [43]:
print b
print np.linalg.det(b)

[[ 1.  0.  0.]
 [ 0.  1.  0.]]


LinAlgError: Last 2 dimensions of the array must be square